(function(){
 'use strict';
 var shapes={L:[[0,0],[.28,0],[.28,.74],[1,.74],[1,1],[0,1]],X:[[0,0],[.32,0],[.5,.32],[.68,0],[1,0],[.68,.5],[1,1],[.68,1],[.5,.68],[.32,1],[0,1],[.32,.5]],Y:[[0,0],[.3,0],[.5,.35],[.7,0],[1,0],[.65,.61],[.65,1],[.35,1],[.35,.61]],Z:[[0,0],[1,0],[1,.23],[.35,.76],[1,.76],[1,1],[0,1],[0,.77],[.65,.24],[0,.24]]};
 function cross(a,b,c){return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);}
 function triangulate(poly){var ids=poly.map(function(_,i){return i;}),out=[],guard=0;while(ids.length>3&&guard++<100){var found=false;for(var k=0;k<ids.length;k++){var a=ids[(k+ids.length-1)%ids.length],b=ids[k],c=ids[(k+1)%ids.length];if(cross(poly[a],poly[b],poly[c])<=0)continue;var inside=ids.some(function(i){return i!==a&&i!==b&&i!==c&&cross(poly[a],poly[b],poly[i])>=0&&cross(poly[b],poly[c],poly[i])>=0&&cross(poly[c],poly[a],poly[i])>=0;});if(inside)continue;out.push([a,b,c]);ids.splice(k,1);found=true;break;}if(!found)break;}if(ids.length===3)out.push(ids);return out;}
 var meshes=Array.from(document.querySelectorAll('.letter')).map(function(el){Array.from(el.childNodes).forEach(function(n){if(n.nodeType===3)n.remove();});var old=el.querySelector('.glyph-volume');if(old)old.remove();var canvas=document.createElement('canvas');canvas.className='wire-glyph';canvas.setAttribute('aria-hidden','true');el.prepend(canvas);var poly=shapes[el.dataset.letter];return {el:el,canvas:canvas,ctx:canvas.getContext('2d'),poly:poly,tri:triangulate(poly)};});
 var ax=-.15,ay=-.3,queued=false,visible=true;var reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 function render(){queued=false;if(!visible)return;meshes.forEach(function(m){var w=m.el.clientWidth,h=m.el.clientHeight,pad=36,dpr=Math.min(devicePixelRatio||1,2);var cw=w+pad*2,ch=h+pad*2;m.canvas.width=cw*dpr;m.canvas.height=ch*dpr;m.canvas.style.width=cw+'px';m.canvas.style.height=ch+'px';m.canvas.style.left=-pad+'px';m.canvas.style.top=-pad+'px';var ctx=m.ctx;ctx.setTransform(dpr,0,0,dpr,0,0);var width=w*.87,height=h*.78,depth=Math.min(58,w*.42);var verts=[];[-depth/2,depth/2].forEach(function(z){m.poly.forEach(function(p){var x=(p[0]-.5)*width,y=(p[1]-.5)*height;var xx=x*Math.cos(ay)+z*Math.sin(ay),zz=-x*Math.sin(ay)+z*Math.cos(ay);var yy=y*Math.cos(ax)-zz*Math.sin(ax);zz=y*Math.sin(ax)+zz*Math.cos(ax);var s=800/(800-zz);verts.push([cw/2+xx*s,ch/2+yy*s,zz]);});});var n=m.poly.length,faces=[];m.tri.forEach(function(t){faces.push({ids:t,front:false});faces.push({ids:t.map(function(i){return i+n;}),front:true});});for(var i=0;i<n;i++){var j=(i+1)%n;faces.push({ids:[i,j,j+n],front:false},{ids:[i,j+n,i+n],front:false});}faces.sort(function(a,b){return a.ids.reduce(function(s,i){return s+verts[i][2];},0)-b.ids.reduce(function(s,i){return s+verts[i][2];},0);});faces.forEach(function(f){ctx.beginPath();f.ids.forEach(function(i,k){var v=verts[i];if(k===0)ctx.moveTo(v[0],v[1]);else ctx.lineTo(v[0],v[1]);});ctx.closePath();ctx.fillStyle=f.front?'#d2d5d1':'#777f7d';ctx.fill();ctx.strokeStyle='#303b39';ctx.lineWidth=.85;ctx.stroke();});});}
 function schedule(){if(!queued){queued=true;requestAnimationFrame(render);}}
 window.addEventListener('pointermove',function(e){if(reduced||e.pointerType==='touch')return;ay=-.3+(e.clientX/innerWidth-.5)*.48;ax=-.15-(e.clientY/innerHeight-.5)*.25;schedule();},{passive:true});
 new ResizeObserver(schedule).observe(document.getElementById('stage'));new IntersectionObserver(function(entries){visible=entries[0].isIntersecting;if(visible)schedule();}).observe(document.getElementById('stage'));schedule();
})();
